# Generated by Django 2.2.4 on 2020-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_name_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='contact_url',
            field=models.URLField(blank=True, help_text='Url of the contact or term and conditions url', max_length=2000, null=True, verbose_name='Contact url'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='imprint',
            field=models.URLField(blank=True, help_text='Enter the URL of the imprint', max_length=2000, null=True, verbose_name='Imprint'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='terms_and_conditions_of_contract_url',
            field=models.URLField(blank=True, help_text='URL to the terms and conditions', max_length=2000, null=True, verbose_name='Terms and conditions of contract'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='url',
            field=models.URLField(help_text='Enter url of the reviewing online shop', max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='checked_website_text_url',
            field=models.URLField(blank=True, help_text='URL of the checked website text', max_length=2000, null=True, verbose_name='Website text'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='checkout_page_address_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the checkout page', max_length=2000, null=True, verbose_name='Checkout page (address)'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='checkout_page_payment_method_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the payment method selection', max_length=2000, null=True, verbose_name='Checkout page (payment method)'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='domain_registration_contradiction_url',
            field=models.URLField(blank=True, help_text='URL of the website if a founding date was specified that does not match the domain registration', max_length=2000, null=True, verbose_name='Contradiction with information on the website'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='domain_whois_url',
            field=models.URLField(blank=True, help_text='Enter URL of the domain query e.g. <a href="https://www.whois.com/whois" target="_blank">www.whois.com/whois</a>', max_length=2000, null=True, verbose_name='Domain WHOIS'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='fictitious_quality_mark_url',
            field=models.URLField(blank=True, help_text='URL of the used fictitious quality mark', max_length=2000, null=True, verbose_name='Fictitious quality mark'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='imprint',
            field=models.URLField(blank=True, help_text='Enter the URL of the imprint', max_length=2000, null=True, verbose_name='Imprint'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='payment_method_assessment',
            field=models.URLField(blank=True, help_text='Enter assessment of payment method', max_length=2000, null=True, verbose_name='Assessment of the payment method'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='price_comparison_geizhals_eu_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the geizhals.eu search', max_length=2000, null=True, verbose_name='Price comparison on geizhals.eu'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='product_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the product page', max_length=2000, null=True, verbose_name='Product page'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='quality_mark_url',
            field=models.URLField(blank=True, help_text='URL of the used quality mark', max_length=2000, null=True, verbose_name='Quality mark image'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='terms_and_conditions_of_contract_url',
            field=models.URLField(blank=True, help_text='URL to the terms and conditions', max_length=2000, null=True, verbose_name='Terms and conditions of contract'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='terms_of_payment_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the terms of payment', max_length=2000, null=True, verbose_name='Terms of payment'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='url',
            field=models.URLField(help_text='Enter url of the reviewing online shop', max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='result_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
