# Generated by Django 2.2.4 on 2020-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0002_auto_20200220_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='payment_method_assessment',
            field=models.CharField(blank=True, help_text='Enter assessment of payment method', max_length=2000, null=True, verbose_name='Assessment of the payment method'),
        ),
    ]
