# Generated by Django 2.2.4 on 2020-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0004_auto_20200221_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageexample',
            name='language_example_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
