# Generated by Django 2.2.4 on 2020-03-18 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0007_website_reported_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReportedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=255, verbose_name='Reporter')),
                ('reporter_de', models.CharField(max_length=255, null=True, verbose_name='Reporter')),
                ('reporter_en_GB', models.CharField(max_length=255, null=True, verbose_name='Reporter')),
            ],
        ),
        migrations.AlterField(
            model_name='website',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='website',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='website',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.WebsiteReportedBy', verbose_name='Reported by'),
        ),
    ]
