# Generated by Django 2.2.4 on 2020-03-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0008_auto_20200318_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitereportedby',
            options={'verbose_name': 'Website reported by', 'verbose_name_plural': 'Websites reported by'},
        ),
    ]
