# Generated by Django 2.2.4 on 2020-03-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0009_auto_20200318_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
            ],
            options={
                'ordering': ('type',),
                'verbose_name': 'Website type',
                'verbose_name_plural': 'Website types',
            },
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.AlterModelOptions(
            name='websitereportedby',
            options={'ordering': ('reporter',), 'verbose_name': 'Website reported by', 'verbose_name_plural': 'Websites reported by'},
        ),
    ]
