# Generated by Django 2.2.4 on 2020-03-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0010_auto_20200319_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.WebsiteType', verbose_name='Website type'),
        ),
    ]
