# Generated by Django 2.2.4 on 2020-03-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0012_auto_20200319_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitereportedby',
            options={'ordering': ('-reporter',), 'verbose_name': 'Website reported by', 'verbose_name_plural': 'Websites reported by'},
        ),
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ('-type',), 'verbose_name': 'Website type', 'verbose_name_plural': 'Website types'},
        ),
        migrations.AddField(
            model_name='mal2counterfeitersdb',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.Website'),
        ),
        migrations.AddField(
            model_name='mal2fakeshopdb',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.Website'),
        ),
    ]
