# Generated by Django 2.2.4 on 2020-03-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0013_auto_20200319_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.Website'),
        ),
    ]
