# Generated by Django 2.2.4 on 2020-03-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0015_auto_20200319_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'permissions': [('check_website', 'Can check website')], 'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
    ]
