# Generated by Django 2.2.4 on 2020-03-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0016_auto_20200319_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='domain_is_counterfeiter',
            field=models.BooleanField(default=False, help_text='Do not tick if no or uncertain assessment.<br><strong>There are more checks necessary if not checked!</strong>', verbose_name='Domain: is brand counterfeiter'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='imprint_is_counterfeiter',
            field=models.BooleanField(default=False, help_text='Do not tick if no or uncertain assessment.<br><strong>There are more checks necessary if not checked!</strong>', verbose_name='Imprint: is brand counterfeiter'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='language_is_counterfeiter',
            field=models.BooleanField(default=False, help_text='Do not tick if no or uncertain assessment.<br><strong>There are more checks necessary if not checked!</strong>', verbose_name='Imprint: is brand counterfeiter'),
        ),
        migrations.AlterField(
            model_name='website',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rating'),
        ),
    ]
