# Generated by Django 2.2.4 on 2020-03-31 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0017_auto_20200323_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRiskScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en_GB', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('risk_score', models.CharField(max_length=50, verbose_name='Risk score')),
            ],
            options={
                'verbose_name': 'Website risk score',
                'verbose_name_plural': 'Website risk scores',
                'ordering': ('-name',),
            },
        ),
        migrations.AlterField(
            model_name='companyname',
            name='company_name_url',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='companyname',
            name='mal2_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='mal2_db.mal2FakeShopDB'),
        ),
        migrations.AlterField(
            model_name='languageexample',
            name='language_example_url',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='languageexample',
            name='mal2_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_example', to='mal2_db.mal2FakeShopDB'),
        ),
        migrations.AlterField(
            model_name='languageurl',
            name='mal2_counterfeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_url', to='mal2_db.mal2CounterfeitersDB'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='contact_url',
            field=models.CharField(blank=True, help_text='Url of the contact or term and conditions url', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Contact url'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='domain_is_counterfeiter',
            field=models.BooleanField(default=False, help_text='Do not tick if no or uncertain assessment.<br><strong>There are more checks necessary if not checked!</strong>', verbose_name='Domain assessment: is certainly a  brand counterfeiter?'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='imprint',
            field=models.CharField(blank=True, help_text='Enter the URL of the imprint', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Imprint'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='imprint_is_counterfeiter',
            field=models.BooleanField(default=False, help_text='Do not tick if no or uncertain assessment.<br><strong>There are more checks necessary if not checked!</strong>', verbose_name='Imprint assessment: is certainly a brand counterfeiter?'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='language_is_counterfeiter',
            field=models.BooleanField(default=False, help_text='Do not tick if no or uncertain assessment.<br><strong>There are more checks necessary if not checked!</strong>', verbose_name='Imprint assessment: is certainly a brand counterfeiter?'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='terms_and_conditions_of_contract_url',
            field=models.CharField(blank=True, help_text='URL to the terms and conditions', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Terms and conditions of contract'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='url',
            field=models.CharField(help_text='Enter url of the reviewing online shop', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='checked_website_text_url',
            field=models.CharField(blank=True, help_text='URL of the checked website text', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website text'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='checkout_page_address_url',
            field=models.CharField(blank=True, help_text='Enter the URL of the checkout page', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Checkout page (address)'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='checkout_page_payment_method_url',
            field=models.CharField(blank=True, help_text='Enter the URL of the payment method selection', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Checkout page (payment method)'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='domain_registration_contradiction_url',
            field=models.CharField(blank=True, help_text='URL of the website if a founding date was specified that does not match the domain registration', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Contradiction with information on the website'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='domain_whois_url',
            field=models.CharField(blank=True, help_text='Enter URL of the domain query e.g. <a href="https://www.whois.com/whois" target="_blank">www.whois.com/whois</a>', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Domain WHOIS'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='fictitious_quality_mark_url',
            field=models.CharField(blank=True, help_text='URL of the used fictitious quality mark', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Fictitious quality mark'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='imprint',
            field=models.CharField(blank=True, help_text='Enter the URL of the imprint', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Imprint'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='price_comparison_geizhals_eu_url',
            field=models.CharField(blank=True, help_text='Enter the URL of the geizhals.eu search', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Price comparison on geizhals.eu'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='product_url',
            field=models.CharField(blank=True, help_text='Enter the URL of the product page', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Product page'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='quality_mark_url',
            field=models.CharField(blank=True, help_text='URL of the used quality mark', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Quality mark image'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='terms_and_conditions_of_contract_url',
            field=models.CharField(blank=True, help_text='URL to the terms and conditions', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Terms and conditions of contract'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='terms_of_payment_url',
            field=models.CharField(blank=True, help_text='Enter the URL of the terms of payment', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Terms of payment'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='url',
            field=models.CharField(help_text='Enter url of the reviewing online shop', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='productexample',
            name='mal2_counterfeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_example', to='mal2_db.mal2CounterfeitersDB'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='mal2_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_result', to='mal2_db.mal2FakeShopDB'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='result_url',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(help_text='Enter url of the reviewing website', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='mal2_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_image', to='mal2_db.mal2FakeShopDB'),
        ),
        migrations.AlterField(
            model_name='websitetext',
            name='mal2_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_text', to='mal2_db.mal2FakeShopDB'),
        ),
        migrations.AlterField(
            model_name='websitetext',
            name='website_text_url',
            field=models.CharField(blank=True, help_text='URL of the checked text', max_length=2000, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
    ]
