# Generated by Django 2.2.4 on 2020-03-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0018_auto_20200331_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteriskscore',
            options={'ordering': ('-id',), 'verbose_name': 'Website risk score', 'verbose_name_plural': 'Website risk scores'},
        ),
        migrations.RemoveField(
            model_name='website',
            name='rating',
        ),
        migrations.AddField(
            model_name='website',
            name='risk_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.WebsiteRiskScore', verbose_name='Risk score'),
        ),
    ]
