# Generated by Django 2.2.4 on 2020-04-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0019_auto_20200331_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
