# Generated by Django 2.2.4 on 2020-04-01 12:47

from django.db import migrations
import django.utils.timezone
import mal2.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0020_auto_20200401_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='created',
            field=mal2.models.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='modified',
            field=mal2.models.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
