# Generated by Django 2.2.4 on 2020-04-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0022_auto_20200401_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='created_by',
        ),
    ]
