# Generated by Django 2.2.4 on 2020-04-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0023_remove_website_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='modified_by',
        ),
    ]
