# Generated by Django 2.2.4 on 2020-04-01 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0024_remove_website_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_mal2_db_website_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
