# Generated by Django 2.2.4 on 2020-04-01 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0028_auto_20200401_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_mal2_db_website_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
