# Generated by Django 2.2.4 on 2020-04-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0030_auto_20200401_1549'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='created_by',
        ),
        migrations.AddField(
            model_name='website',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mal2_db_website_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
