# Generated by Django 2.2.4 on 2020-04-01 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mal2.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0032_auto_20200401_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteriskscore',
            name='created',
            field=mal2.models.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteriskscore',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mal2_db_websiteriskscore_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='websiteriskscore',
            name='modified',
            field=mal2.models.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='websiteriskscore',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mal2_db_websiteriskscore_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
