# Generated by Django 2.2.4 on 2020-04-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0035_auto_20200402_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='reported_at',
        ),
    ]
