# Generated by Django 2.2.4 on 2020-06-02 07:57

from django.db import migrations, models
import mal2.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0036_remove_website_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='websites/screenshots/'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='created_at',
            field=mal2.models.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='mal2counterfeitersdb',
            name='modified_at',
            field=mal2.models.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='created_at',
            field=mal2.models.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='mal2fakeshopdb',
            name='modified_at',
            field=mal2.models.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=mal2.models.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='website',
            name='modified_at',
            field=mal2.models.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
    ]
