# Generated by Django 2.2.4 on 2020-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0037_auto_20200602_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='screenshot',
            field=models.FilePathField(blank=True, null=True, path='/Users/mh/Documents/Projects/mal2_ui/db/media/websites/screenshots'),
        ),
    ]
