# Generated by Django 2.2.4 on 2020-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0038_auto_20200602_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='screenshot',
            field=models.FilePathField(blank=True, null=True, path='/home/nh/Projekte/Mal2/Mal2_Browser/mal2-ui/db/media/websites/screenshots'),
        ),
    ]
