# Generated by Django 2.2.4 on 2020-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0039_auto_20200715_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Website category',
                'verbose_name_plural': 'Website categories',
                'ordering': ('-category',),
            },
        ),
    ]
