# Generated by Django 2.2.4 on 2020-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0040_websitecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecategory',
            name='category_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='category_en_GB',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='websitecategory',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
    ]
