# Generated by Django 2.2.4 on 2020-07-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0041_auto_20200715_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.WebsiteCategory', verbose_name='Website Category'),
        ),
    ]
