# Generated by Django 2.2.4 on 2020-07-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0043_auto_20200716_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website_category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.WebsiteCategory', verbose_name='Website category'),
        ),
    ]
