# Generated by Django 2.2.4 on 2020-11-11 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0045_auto_20200717_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ('type_de',), 'verbose_name': 'Website type', 'verbose_name_plural': 'Website types'},
        ),
        migrations.AddField(
            model_name='websitetype',
            name='default_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mal2_db.WebsiteCategory', verbose_name='Website category'),
        ),
        migrations.AlterField(
            model_name='website',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='website',
            name='screenshot',
            field=models.FilePathField(blank=True, null=True, path='/Users/mh/Documents/Projects/mal2_ui/db/media/websites/screenshots'),
        ),
    ]
