# Generated by Django 2.2.4 on 2020-12-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal2_db', '0047_websitetype_order_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ('ordering_index', 'type_de'), 'verbose_name': 'Website type', 'verbose_name_plural': 'Website types'},
        ),
        migrations.RenameField(
            model_name='websitetype',
            old_name='order_index',
            new_name='ordering_index',
        ),
    ]
